version: '3'

# If we're using env vars, for the compose container_name and host (for a connection string) should be the same

services:
  db:
    image: postgres
    restart: always
    container_name: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
  cache:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env
    volumes:
      - redis:/var/lib/redis/data
    depends_on:
      - db
  app:
    container_name: juntos-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:8080
    depends_on:
      - db
      - cache
    env_file:
      - .env
    volumes:
      - .:/usr/app
volumes:
  postgres:
  redis:
