"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createCustomerUseCase = exports.createCustomerController = exports.customerRepository = void 0;
const CreateCustomerController_1 = require("../infrastructure/controllers/CreateCustomerController");
const AxiosCustomerRepository_1 = require("../infrastructure/repositories/AxiosCustomerRepository");
const createCustomer_1 = require("../useCases/createCustomer");
const customerRepository = new AxiosCustomerRepository_1.AxiosCustomerRepository();
exports.customerRepository = customerRepository;
const createCustomerUseCase = new createCustomer_1.CreateCustomerUseCase(customerRepository);
exports.createCustomerUseCase = createCustomerUseCase;
const createCustomerController = new CreateCustomerController_1.CreateCustomerController(createCustomerUseCase);
exports.createCustomerController = createCustomerController;
