"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UPDATE_EMPLOYEE = exports.RETRIEVE_EMPLOYEES_ERROR = exports.RETRIEVE_EMPLOYEE_ERROR = exports.EMPLOYEE_DOESNT_EXIST = exports.EMPLOYEE_EXISTS = exports.ONLY_POST_METHOD = exports.INVALID_REQUEST_WITH_EMAIL = exports.INVALID_REQUEST_WITH_ID = exports.RETRIEVE_ONCREATE_EMPLOYEE_ERROR = exports.NO_SUCH_EMPLOYEE_ERROR = exports.CREATE_EMPLOYEE_ERROR = exports.CACHE_KEY = exports.BASE_URL = void 0;
exports.BASE_URL = 'http://localhost:3004/employees';
exports.CACHE_KEY = 'employees';
exports.CREATE_EMPLOYEE_ERROR = 'It was not possible to create the employee';
exports.NO_SUCH_EMPLOYEE_ERROR = 'There is no employee with this email';
exports.RETRIEVE_ONCREATE_EMPLOYEE_ERROR = 'Something went wrong. Please, check if employee was created or try again!';
exports.INVALID_REQUEST_WITH_ID = 'Invalid request using such id. Please, try again!';
exports.INVALID_REQUEST_WITH_EMAIL = 'Invalid request using such email. Please, try again!';
exports.ONLY_POST_METHOD = 'Only POST requests methods allowed';
exports.EMPLOYEE_EXISTS = 'Employee already exists';
exports.EMPLOYEE_DOESNT_EXIST = 'This employee doesn\'t exist';
exports.RETRIEVE_EMPLOYEE_ERROR = 'It was not possible to get this employee';
exports.RETRIEVE_EMPLOYEES_ERROR = 'It was not possible to get the employees';
exports.UPDATE_EMPLOYEE = 'It was not possible to update this employee';
