export const BASE_URL = 'http://localhost:3004/employees'
export const CACHE_KEY = 'employees'

export const CREATE_EMPLOYEE_ERROR = 'It was not possible to create the employee'
export const NO_SUCH_EMPLOYEE_ERROR = 'There is no employee with this email'
export const RETRIEVE_ONCREATE_EMPLOYEE_ERROR = 'Something went wrong. Please, check if employee was created or try again!'
export const INVALID_REQUEST_WITH_ID = 'Invalid request using such id. Please, try again!'
export const INVALID_REQUEST_WITH_EMAIL = 'Invalid request using such email. Please, try again!'
export const ONLY_POST_METHOD = 'Only POST requests methods allowed'
export const EMPLOYEE_EXISTS = 'Employee already exists'
export const EMPLOYEE_DOESNT_EXIST = 'This employee doesn\'t exist'
export const RETRIEVE_EMPLOYEE_ERROR = 'It was not possible to get this employee'
export const RETRIEVE_EMPLOYEES_ERROR = 'It was not possible to get the employees'
export const UPDATE_EMPLOYEE = 'It was not possible to update this employee'
